"""user comments relations test

Revision ID: 369f96ecc53f
Revises: 81a33de9d375
Create Date: 2018-01-03 11:23:17.747994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '369f96ecc53f'
down_revision = '81a33de9d375'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'user_id')
    # ### end Alembic commands ###
