"""changed categori id name

Revision ID: 64841d406346
Revises: 1a80499433e2
Create Date: 2018-01-05 17:58:32.714123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64841d406346'
down_revision = '1a80499433e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_column('pitches', 'cagory_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('cagory_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'category_id')
    # ### end Alembic commands ###
